import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {resolve,join,sep} from 'node:path';
import {once} from 'node:events';
const base='http://localhost:3197',password='Test-Only-Printio-Password-2026';
let child,dir,cookie,config,reference;
async function request(path,method='GET',body,auth=false,headers={}){return fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(auth?{cookie}:{}),...headers},body:body?JSON.stringify(body):undefined});}
async function start(){child=spawn(process.execPath,['server.mjs'],{cwd:resolve('.'),env:{...process.env,PORT:'3197',DATA_DIR:dir,ADMIN_PASSWORD:password},stdio:['ignore','pipe','pipe']});await new Promise((ok,bad)=>{child.stdout.on('data',b=>{if(b.toString().includes('http://'))ok()});child.on('error',bad);child.on('exit',c=>bad(new Error('Server exited '+c)));});}
async function stop(){const done=once(child,'exit');child.kill();await done;}
before(async()=>{dir=await mkdtemp(join(resolve('.'),'printio-test-'));await start();config=await (await request('/api/config')).json();});
after(async()=>{await stop();const target=resolve(dir);assert.ok(target.startsWith(resolve('.')+sep)&&target.split(sep).at(-1).startsWith('printio-test-'));await rm(target,{recursive:true,force:true});});
test('Public catalog includes supplied designs and no private orders',async()=>{assert.ok(config.models.some(m=>m.id==='snoopy'));assert.equal((await request('/api/admin/dashboard')).status,401);assert.equal((await request('/data/printio.sqlite')).status,404);});
test('Authentication rejects wrong password and cross-origin requests',async()=>{assert.equal((await request('/api/admin/login','POST',{password:'wrong'})).status,401);assert.equal((await request('/api/admin/login','POST',{password},false,{origin:'https://untrusted.example'})).status,403);const r=await request('/api/admin/login','POST',{password});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);cookie=r.headers.get('set-cookie').split(';')[0];});
test('Server calculates price, validates variants and persists order',async()=>{const body={name:'Client test',phone:'+37360000000',method:'message',lang:'ro',notes:'Test automat',items:[{kind:'model',modelId:'snoopy',size:'M',color:'#f1f0eb',quantity:2,price:1}],estimatedTotal:1};const r=await request('/api/orders','POST',body);assert.equal(r.status,201);const result=await r.json();assert.equal(result.estimatedTotal,950);reference=result.reference;body.items[0].size='INVALID';assert.equal((await request('/api/orders','POST',body)).status,400);const dashboard=await (await request('/api/admin/dashboard','GET',null,true)).json();assert.equal(dashboard.orders[0].reference,reference);assert.equal(dashboard.orders[0].items[0].size,'M');assert.equal((await request('/api/admin/orders/'+dashboard.orders[0].id,'PATCH',{status:'completed'},true)).status,200);});
test('Upload checks file format; admin can add and edit products',async()=>{assert.equal((await request('/api/upload','POST',{type:'image/png',data:Buffer.from('not png').toString('base64')})).status,400);const bytes=await readFile('public/assets/snoopy.jpg');const upload=await (await request('/api/upload','POST',{type:'image/jpeg',data:bytes.toString('base64')})).json();assert.ok(upload.imageId);const product={id:'test-model',kind:'model',name:{ro:'Test model',ru:'Тест'},description:{ro:'Descriere',ru:'Описание'},image:upload.url,product:'tshirt',price:300};assert.equal((await request('/api/admin/products','POST',product)).status,401);assert.equal((await request('/api/admin/products','POST',product,true)).status,201);product.price=350;assert.equal((await request('/api/admin/products','POST',product,true)).status,201);const c=await (await request('/api/config')).json();assert.equal(c.models.filter(m=>m.id==='test-model').length,1);assert.equal(c.prices.models['test-model'],350);const newBase={...product,id:'test-base',kind:'base',template:'hoodie',sizes:['S','M'],colors:['#ffffff'],price:400};assert.equal((await request('/api/admin/products','POST',newBase,true)).status,201);const updated=await (await request('/api/config')).json();assert.ok(updated.areas['test-base'].front);});
test('Custom orders validate print coordinates and use shared pricing',async()=>{const design={product:'tshirt',color:'#f1f0eb',size:'M',quantity:1,layers:[{id:'text-1',type:'text',side:'front',x:20,y:20,width:60,height:22,rotation:0,text:'Salut',color:'#211c19'}]};const body={name:'Test editor',phone:'+37360000000',method:'call',lang:'ru',notes:'',items:[{kind:'custom',quantity:1,design}]};const r=await request('/api/orders','POST',body);assert.equal(r.status,201);assert.ok((await r.json()).estimatedTotal>160);design.layers[0].x=90;assert.equal((await request('/api/orders','POST',body)).status,400);});
test('Statistics record real views, and data survives server restart',async()=>{assert.equal((await request('/api/visit','POST',{path:'/modele'})).status,200);let d=await (await request('/api/admin/dashboard','GET',null,true)).json();assert.equal(d.pages.find(p=>p.path==='/modele').views,1);await stop();await start();assert.equal((await request('/api/admin/dashboard','GET',null,true)).status,401);const r=await request('/api/admin/login','POST',{password});cookie=r.headers.get('set-cookie').split(';')[0];d=await (await request('/api/admin/dashboard','GET',null,true)).json();assert.equal(d.orders.find(o=>o.reference===reference).status,'completed');assert.equal(d.config.prices.models['test-model'],350);assert.equal(d.pages.find(p=>p.path==='/modele').views,1);await request('/api/admin/logout','POST',{},true);assert.equal((await request('/api/admin/dashboard','GET',null,true)).status,401);});
